version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: spring3
      POSTGRES_PASSWORD: spring3
      POSTGRES_DB: spring3
      TZ: "Europe/Stockholm"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

