spring:
  application:
    name: spring3-test
  profiles:
    active: local-oracle
    group:
      local-oracle: oracle-db
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/spring3
    username: spring3
    password: spring3
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.datasource.username}
    show-sql: false
    open-in-view: false
  flyway:
    clean-disabled: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres


solace:
  jms:
    host: localhost:55554
    username: admin
    password: admin
    vpn: default
    maxRetries: 2


logging:
  level:
    root: INFO
    com.solacesystems: info

---
spring.config.activate.on-profile: postgres-db
spring:
  flyway:
    default-schema:  ${spring.jpa.properties.hibernate.default_schema}

